spring:
  datasource:
    url: jdbc:h2:mem:test
    username: db_user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.hibernate.SQL: debug